### ISSUE TITLE
keys

### ISSUE THREAD

**Issue by Lamperoyge** [outdoteth/putty-frontend#1]
hi, found your project on reddit and wanted to check the repos and I couldn't message you on twitter so leaving this here, you should probably hide https://github.com/outdoteth/putty-frontend/blob/dev/firebase.js

**Comment by outdoteth** [comment]
Hey man, thanks for checking it out! Those keys are fine to leave open tho since they are just identifiers.
Btw idk if you've joined but there is a discord too if you want to join the (small but growing) community https://discord.com/invite/TScUmZYw
